# Generated by Django 4.2.10 on 2024-02-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(help_text='name it in lower case, seperated by spaces (min 2 words)', max_length=299),
        ),
    ]
